{
 "title": "Kubernetes Storage Volumes (Cluster)",
 "description": "Shows information and alerts related to Kubernetes Storage / Volumes (cluster level).",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "k8s_cluster_name", "label": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } },
   {
    "name": "ping_cloud_namespace",
    "label": "Ping-cloud namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "80"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  count (\n    (predict_linear(kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace!=\"$ping_cloud_namespace\"}[1d], 7 * 24 * 60 * 60) <= 0)\n  )\n)\nor\nvector(0)",
       "legendFormat": "alerts"
      }
     ]
    },
    {
     "title": "Ping-cloud Namespace Volumes Full in Week Based on Daily Use Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  count (\n    (predict_linear(kubelet_volume_stats_available_bytes{k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$ping_cloud_namespace\"}[1d], 7 * 24 * 60 * 60) <= 0)\n  )\n)\nor\nvector(0)",
       "legendFormat": "alerts"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
      }
     ]
    },
    {
     "title": "Unbound PVCs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count(kube_persistentvolumeclaim_status_phase{k8s_cluster_name=~\"$k8s_cluster_name\",job=\"kube-state-metrics\",phase!=\"Bound\"} > 0) or (vector(0)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Alert Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Current",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "  (\n    predict_linear((sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace!~\"$ping_cloud_namespace\"})[1d:10m]),7 * 24 * 60 * 60) \n    <= \n    0 \n  )"
      }
     ]
    },
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Alert History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "# of Alerts" }
     ],
     "targets": [
      {
       "expr": "count (\n  (\n    predict_linear((sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace!~\"$ping_cloud_namespace\"})[1d:10m]),7 * 24 * 60 * 60) \n    <= \n    0 \n  )\n)",
       "legendFormat": "Alerts - Volumes Full in Week Based on Daily Use Rate (Infrastructure)"
      }
     ]
    },
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Predicted Available Space History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "1 Week Predicted Available Space"
      }
     ],
     "targets": [
      {
       "expr": "predict_linear((sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace!~\"$ping_cloud_namespace\"})[1d:10m]), 7 * 24 * 60 * 60)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Ping-cloud Namespace Volumes Full in Week Based on Daily Use Rate - Current",
     "type": "table-old",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "  (\n    predict_linear((sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=~\"$ping_cloud_namespace\"})[1d:10m]),7 * 24 * 60 * 60) \n    <= \n    0 \n  )"
      }
     ]
    },
    {
     "title": "Ping-cloud Namespace Volumes Full in Week Based on Daily Use Rate - Alert History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "# of Alerts" }
     ],
     "targets": [
      {
       "expr": "count (\n  (\n    predict_linear((sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=~\"$ping_cloud_namespace\"})[1d:10m]),7 * 24 * 60 * 60) \n    <= \n    0 \n  )\n)",
       "legendFormat": "Alerts - Volumes Full in Week Based on Daily Use Rate (Ping-cloud Namespace: $ping_cloud_namespace)"
      }
     ]
    },
    {
     "title": "Ping-cloud Namespace Volumes Full in Week Based on Daily Use Rate - Predicted Available Space History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 22 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "1 Week Predicted Available Space"
      }
     ],
     "targets": [
      {
       "expr": "predict_linear((sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=~\"$ping_cloud_namespace\"})[1d:10m]), 7 * 24 * 60 * 60)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold Stats - Current",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "(kube_persistentvolumeclaim_info{k8s_cluster_name=~\"$k8s_cluster_name\"}) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) >= ($pvc_percent_used_warning_threshold / 100)"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold - History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Total # of Alerts" }
     ],
     "targets": [
      {
       "expr": "(\n  ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) * 0 +1)\n  and\n  (\n    (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"}))\n  ) >= ($pvc_percent_used_warning_threshold / 100)\n)",
       "legendFormat": "Alerts - PVC Running Above % Used Warning Threshold ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bound PVCs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum (kube_persistentvolumeclaim_status_phase{k8s_cluster_name=~\"$k8s_cluster_name\",job=\"kube-state-metrics\",phase=\"Bound\"} ==1 )) or vector(0)"
      }
     ]
    },
    {
     "title": "PVC Stats",
     "type": "table-old",
     "gridPos": { "h": 25, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_info{k8s_cluster_name=~\"$k8s_cluster_name\",job=\"kube-state-metrics\"}"
      },
      {
       "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info{k8s_cluster_name=~\"$k8s_cluster_name\"} ) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info{k8s_cluster_name=~\"$k8s_cluster_name\"} ) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )))"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"})"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} ))"
      }
     ]
    }
   ]
  },
  {
   "title": "Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All Running PVCs Used Bytes",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} ))",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Running PVCs % Used",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\"} )) * 100",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Use Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hourly Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(\n  (sum by (namespace, persistentvolumeclaim) (\n    kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\"}))[1h:1m]\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(\n  (sum by (namespace, persistentvolumeclaim) (\n    kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\"}))[1d:10m]\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Weekly Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(\n  (sum by (namespace, persistentvolumeclaim) (\n    kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\"}))[1w:1h]\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  }
 ]
}