{
 "title": "Logging metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit incoming events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_input_records_total{k8s_cluster_name=~\"$cluster_name\",name=~\"tail.*\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fluent-bit outgoing events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_output_proc_records_total{k8s_cluster_name=~\"$cluster_name\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logstash incoming events per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_in_total{k8s_cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pipeline}} pipe on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash outgoing events per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_out_total{k8s_cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pipeline}} pipe on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash events in queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "logstash_node_queue_events{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pipeline}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "logstash_node_mem_heap_max_bytes{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Heap max on {{instance}}"
    },
    {
     "expr": "logstash_node_mem_heap_used_bytes",
     "legendFormat": "Heap used on {{instance}}"
    }
   ]
  }
 ]
}