{
 "title": "PingOne Advanced Services Ingress Usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ingressName",
    "query": {
     "query": "label_values(kube_ingress_labels,ingress)"
    }
   },
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"$ingressName\",k8s_cluster_name=~\"$cluster_name\"}[5m]) * 60) by (status)",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "Bytes transferred / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_bytes_sent_sum{ingress=\"$ingressName\",k8s_cluster_name=~\"$cluster_name\"}[5m]) * 60) by (path, status)",
     "legendFormat": "Path: {{path}} - Status: {{status}}"
    },
    { "expr": "ingress" }
   ]
  },
  {
   "title": "Backend requests / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_count{ingress=\"$ingressName\",k8s_cluster_name=~\"$cluster_name\"}[5m]) * 60) by (method, status)",
     "legendFormat": "{{method}} - Status: {{status}}"
    }
   ]
  },
  {
   "title": "Average response time ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_response_duration_seconds_count{ingress=\"$ingressName\",k8s_cluster_name=~\"$cluster_name\"}[5m])*1000) by (method, status)",
     "legendFormat": "{{method}} - Status: {{status}}"
    }
   ]
  },
  {
   "title": "Maximum response time ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(rate(nginx_ingress_controller_response_duration_seconds_count{ingress=\"$ingressName\",k8s_cluster_name=~\"$cluster_name\"}[5m])*1000) by (method, status)",
     "legendFormat": "{{method}} - Status: {{status}}"
    }
   ]
  },
  {
   "title": "Ingress percentile response times ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",ingress=~\"$ingressName\", k8s_cluster_name=~\"$cluster_name\"}[2m])) by (le, ingress))*1000",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",ingress=~\"$ingressName\", k8s_cluster_name=~\"$cluster_name\"}[2m])) by (le, ingress))*1000",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",ingress=~\"$ingressName\", k8s_cluster_name=~\"$cluster_name\"}[2m])) by (le, ingress))*1000",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",ingress=~\"$ingressName\", k8s_cluster_name=~\"$cluster_name\"}[2m])) by (le, ingress))*1000",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}