{
 "title": "PingFederate Topology Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Failed SSOs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event: SSO AND status: failure AND role: IdP AND NOT connectionId: healthcheckconnection AND cluster_name: $cluster_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Successful SSOs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event: SSO AND status: success AND role: IdP AND NOT connectionId: healthcheckconnection AND cluster_name: $cluster_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(event: AUTHN_ATTEMPT AND status: failure AND NOT connectionId: healthcheckconnection AND cluster_name: $cluster_name) OR (status:inprogress AND event:AUTHN_ATTEMPT AND subject:* AND NOT connectionId: healthcheckconnection AND cluster_name: $cluster_name)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event: AUTHN_ATTEMPT AND NOT connectionId: healthcheckconnection AND cluster_name: $cluster_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Admin API Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT clientIp: 127.0.0.1 AND NOT connectionId: healthcheckconnection AND cluster_name: $cluster_name",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}